import {
  Heart,
  HeartPulse,
  Smile,
  Shield,
  Briefcase,
  Scale,
  Zap,
  CheckCircle2,
  Handshake,
  HandHeart,
  GraduationCap,
  ShieldCheck,
  Lock,
  Leaf,
  Users,
  Clock,
  Sparkles,
  Globe,
  Star,
  Anchor,
  Baby,
  TrendingUp,
  UserCheck,
  ShoppingBag,
  type LucideIcon,
} from 'lucide-react';

export interface Value {
  id: string;
  title: string;
  description: string;
  icon: LucideIcon;
  category?: string;
  bulletPoints: string[];
}

export const values: Value[] = [
  {
    id: 'family',
    title: 'Family & relationships',
    description: 'Support loved ones, send remittances, plan for future generations.',
    icon: Heart,
    category: 'Personal',
    bulletPoints: [
      'Highlight that bitcoin makes it easy to send money to loved ones anywhere in the world without expensive remittance fees or banking delays.',
      'Emphasise that self‑custody lets families hold their savings without fearing bank closures or seizures.',
      'Note that bitcoin can serve as a long‑term store of value that families can pass down to future generations.',
    ],
  },
  {
    id: 'health',
    title: 'Health & well‑being',
    description: 'Preserve purchasing power for healthcare, access funds 24/7, support medical crowdfunding.',
    icon: HeartPulse,
    category: 'Personal',
    bulletPoints: [
      'Explain that bitcoin\'s limited supply aims to preserve purchasing power over the long term, helping people afford healthcare even when fiat currencies lose value.',
      'Point out that 24/7 global markets allow people with shifting schedules (e.g., carers or shift workers) to access or send funds whenever needed.',
      'Mention that communities have used bitcoin to fund medical expenses quickly through crowdfunding campaigns without intermediaries.',
    ],
  },
  {
    id: 'happiness',
    title: 'Happiness & personal fulfillment',
    description: 'Control your own money, deepen financial literacy, join a welcoming community.',
    icon: Smile,
    category: 'Personal',
    bulletPoints: [
      'Emphasise the satisfaction of controlling your own money and not relying on banks or governments.',
      'Suggest that learning about bitcoin can deepen financial literacy and give people a sense of empowerment.',
      'Note that bitcoin communities often organise meet‑ups and conferences, offering a sense of belonging and purpose for enthusiasts.',
    ],
  },
  {
    id: 'financial-stability',
    title: 'Financial stability & independence',
    description: 'Protect savings from inflation, secure coins independently, hedge against currency volatility.',
    icon: Shield,
    category: 'Financial',
    bulletPoints: [
      'Explain that bitcoin\'s supply is capped and its issuance schedule is known in advance, so holders aren\'t subject to unexpected monetary debasement.',
      'Highlight that saving in bitcoin can be a hedge against inflation in countries where local currencies are volatile.',
      'Stress that individuals can secure their own coins with a hardware wallet, making them independent of banks.',
    ],
  },
  {
    id: 'employment',
    title: 'Employment & meaningful work',
    description: 'New job opportunities, global freelance payments, innovative business models.',
    icon: Briefcase,
    category: 'Financial',
    bulletPoints: [
      'Point out that the cryptocurrency sector creates jobs in software development, security, education and customer support.',
      'Explain that freelancers can be paid in bitcoin by clients worldwide without waiting for international bank transfers.',
      'Mention that bitcoin enables new business models, such as micro‑work and micro‑tipping.',
    ],
  },
  {
    id: 'fairness',
    title: 'Fairness & equality',
    description: 'Open network for everyone, no gatekeepers, direct access to value transfer.',
    icon: Scale,
    category: 'Social',
    bulletPoints: [
      'Emphasise that the bitcoin network is open; anyone can use it regardless of nationality, income or status.',
      'Note that transactions are processed by miners following strict protocol rules-there are no gatekeepers who can discriminate against users.',
      'Point out that bitcoin reduces reliance on institutions that may perpetuate inequities, giving people direct access to value transfer.',
    ],
  },
  {
    id: 'freedom',
    title: 'Freedom & personal autonomy',
    description: 'Permissionless transactions, complete control over assets, lifeline in authoritarian regimes.',
    icon: Zap,
    category: 'Social',
    bulletPoints: [
      'Stress that bitcoin transactions are permissionless; users do not need approval from banks or governments to send or receive funds.',
      'Explain that holding your own keys gives you complete control over your assets, reinforcing personal sovereignty.',
      'Mention that bitcoin can act as a lifeline for people living under authoritarian regimes where traditional financial systems are restricted.',
    ],
  },
  {
    id: 'honesty',
    title: 'Honesty & integrity',
    description: 'Open, auditable ledger, code-enforced rules, transparent open-source development.',
    icon: CheckCircle2,
    category: 'Social',
    bulletPoints: [
      'Point out that bitcoin\'s blockchain is an open, auditable ledger-anyone can verify transactions, which discourages fraud.',
      'Explain that the protocol\'s rules are enforced by code and consensus, not by arbitrary decision‑making.',
      'Emphasise that developers publish open‑source code, encouraging transparency and peer review.',
    ],
  },
  {
    id: 'respect',
    title: 'Respect & trust',
    description: 'Cryptography-based security, public ledger transparency, accountability through verification.',
    icon: Handshake,
    category: 'Social',
    bulletPoints: [
      'Highlight that bitcoin eliminates the need to trust third parties; instead, it uses cryptography and consensus mechanisms to secure transactions.',
      'Explain that because the ledger is public, no one can secretly create extra coins or alter past transactions.',
      'Note that this transparency can build trust among people who value accountability.',
    ],
  },
  {
    id: 'kindness',
    title: 'Kindness, compassion & helping others',
    description: 'Fast, low-cost donations, quick relief fundraising, more money reaches those in need.',
    icon: HandHeart,
    category: 'Social',
    bulletPoints: [
      'Mention that bitcoin enables fast, low‑cost donations to charities and people in crisis, even across borders.',
      'Explain that communities can raise funds quickly for relief efforts without waiting for wire transfers or approval from crowdfunding platforms.',
      'Point out that some organisations accept bitcoin to avoid high credit‑card fees, so more of a donor\'s money reaches those in need.',
    ],
  },
  {
    id: 'education',
    title: 'Education & knowledge',
    description: 'Learn how money works, access free resources, prepare children for digital economy.',
    icon: GraduationCap,
    category: 'Personal',
    bulletPoints: [
      'Encourage people to learn about how money works by studying bitcoin\'s design, fostering broader financial literacy.',
      'Highlight that many educational resources about bitcoin are freely available online and in multiple languages.',
      'Suggest that teaching children about digital currency can prepare them for an increasingly digital economy.',
    ],
  },
  {
    id: 'safety',
    title: 'Safety & security',
    description: 'More secure than cash, strong cryptography, hardware wallet protection.',
    icon: ShieldCheck,
    category: 'Personal',
    bulletPoints: [
      'Explain that, when properly stored, bitcoin can be more secure than keeping large amounts of cash at home or trusting unstable banks.',
      'Emphasise that transactions use strong cryptography and the network has operated continuously for over a decade without being hacked.',
      'Suggest using hardware wallets and multi‑signature setups to enhance personal security.',
    ],
  },
  {
    id: 'privacy',
    title: 'Privacy & property rights',
    description: 'Protect identity, prove ownership with keys, advanced privacy techniques available.',
    icon: Lock,
    category: 'Personal',
    bulletPoints: [
      'Note that bitcoin transactions do not require users to reveal their identity; they can protect privacy better than credit‑card payments.',
      'Explain that holding private keys proves ownership of funds-no one can seize your coins without those keys.',
      'Mention that advanced techniques (e.g., CoinJoin) can further improve transaction privacy for those who need it.',
    ],
  },
  {
    id: 'environmental',
    title: 'Environmental sustainability & nature',
    description: 'Renewable energy mining, methane capture projects, investment in green infrastructure.',
    icon: Leaf,
    category: 'Social',
    bulletPoints: [
      'Acknowledge concerns about energy use but point out that bitcoin mining is increasingly powered by renewable energy and can stabilise grids by buying excess power.',
      'Highlight projects where miners capture methane from oilfields or landfills to mine bitcoin, reducing greenhouse‑gas emissions.',
      'Explain that bitcoin\'s incentives can drive investment in renewable infrastructure, especially in remote areas.',
    ],
  },
  {
    id: 'community',
    title: 'Community & belonging',
    description: 'Global network of users, local meet-ups, open-source community support.',
    icon: Users,
    category: 'Social',
    bulletPoints: [
      'Emphasise the vibrant global network of bitcoin users and developers who welcome newcomers and help educate them.',
      'Mention local meet‑ups, online forums and conferences where people share experiences and build friendships.',
      'Suggest that supporting open‑source projects and decentralised communities can foster a sense of belonging.',
    ],
  },
  {
    id: 'efficiency',
    title: 'Efficiency & convenience',
    description: 'Fast settlement times, Lightning Network for instant payments, QR code simplicity.',
    icon: Clock,
    category: 'Financial',
    bulletPoints: [
      'Highlight that bitcoin transactions can settle in minutes, even on weekends or holidays, unlike bank transfers.',
      'Explain that the Lightning Network enables instant, low‑cost payments ideal for small purchases.',
      'Note that anyone with a smartphone can scan a QR code to pay, simplifying transactions.',
    ],
  },
  {
    id: 'simplicity',
    title: 'Simplicity & ease‑of‑use',
    description: 'Modern wallets simplify complexity, divisible into satoshis, start small and learn.',
    icon: Sparkles,
    category: 'Personal',
    bulletPoints: [
      'Point out that modern wallets abstract away much of the complexity-users can send or receive by scanning a code or clicking a link.',
      'Explain that bitcoin is divisible into tiny units called satoshis, making it practical for everyday transactions.',
      'Emphasise that people can start with small amounts and gradually learn more as they gain confidence.',
    ],
  },
  {
    id: 'inclusion',
    title: 'Inclusion, diversity & accessibility',
    description: 'Bank the unbanked, no credit checks, initiatives for underrepresented communities.',
    icon: Globe,
    category: 'Social',
    bulletPoints: [
      'Note that billions of people worldwide are unbanked; bitcoin allows them to participate in the global economy with only an internet connection.',
      'Emphasise that there is no credit check or paperwork to open a bitcoin wallet, removing barriers faced by marginalized groups.',
      'Highlight initiatives that teach women and underrepresented communities about bitcoin and provide tools in local languages.',
    ],
  },
  {
    id: 'faith',
    title: 'Faith & spirituality',
    description: 'Sound money principles, transparent charity donations, ethical fund tracking.',
    icon: Star,
    category: 'Personal',
    bulletPoints: [
      'For those who value stewardship, frame bitcoin as "sound money" that cannot be inflated away, aligning with principles of honest weights and measures.',
      'Mention that some faith‑based charities accept bitcoin donations, allowing transparent tracking of funds.',
      'Emphasise ethical considerations-bitcoin\'s open ledger ensures that funds are used as intended.',
    ],
  },
  {
    id: 'stability',
    title: 'Stability & reliability',
    description: 'Continuous operation since 2009, predictable supply schedule, dollar-cost averaging strategies.',
    icon: Anchor,
    category: 'Financial',
    bulletPoints: [
      'Point out that the bitcoin protocol has run continuously since 2009 without downtime.',
      'Explain that the supply schedule is predetermined and halving events reduce new issuance predictably.',
      'Acknowledge price volatility but note that savings strategies like dollar‑cost averaging can smooth out short‑term fluctuations.',
    ],
  },
  {
    id: 'future-generations',
    title: 'Future generations & legacy',
    description: 'Preserve wealth for children, cross-border transfers, time-locked inheritance options.',
    icon: Baby,
    category: 'Personal',
    bulletPoints: [
      'Emphasise that because the supply is finite, holding bitcoin can be a way to preserve wealth for children and grandchildren.',
      'Note that bitcoin can be transferred across borders without inheritance taxes or complex probate if planned correctly.',
      'Suggest using multi‑signature or time‑locked wallets to pass funds on when children reach adulthood.',
    ],
  },
  {
    id: 'wealth',
    title: 'Wealth & prosperity',
    description: 'Historical long-term appreciation, digital gold allocation, fractional ownership access.',
    icon: TrendingUp,
    category: 'Financial',
    bulletPoints: [
      'Explain that bitcoin\'s scarcity and growing adoption have historically driven long‑term price appreciation, though past performance doesn\'t guarantee future results.',
      'Mention that some investors see bitcoin as "digital gold" and allocate a small portion of their portfolio to it as a potential store of value.',
      'Highlight that owning even a fraction of a bitcoin allows participation in a new asset class.',
    ],
  },
  {
    id: 'self-reliance',
    title: 'Self‑reliance & independence',
    description: 'Self-custody without institutions, protection from capital controls, peer-to-peer transactions.',
    icon: UserCheck,
    category: 'Personal',
    bulletPoints: [
      'Stress that self‑custody means you hold your own money without relying on any institution.',
      'Explain that in regions with capital controls or bank freezes, bitcoin can provide an exit route to protect savings.',
      'Mention that users can transact peer‑to‑peer without intermediaries, reinforcing independence.',
    ],
  },
  {
    id: 'ethical-consumption',
    title: 'Ethical consumption & social good',
    description: 'Stranded renewable energy use, fair trade support, fairer financial services.',
    icon: ShoppingBag,
    category: 'Social',
    bulletPoints: [
      'Highlight projects where bitcoin miners use stranded renewable energy, turning wasted resources into economic value.',
      'Mention that bitcoin can support fair trade and human‑rights initiatives by enabling transparent donations.',
      'Emphasise that decentralised finance (DeFi) built on bitcoin aims to create fairer financial services without predatory fees.',
    ],
  },
];

