import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { email, firstName, guideContent, selectedValuesData } = await request.json();

    // Validate required fields
    if (!email) {
      return NextResponse.json(
        { error: 'Email address is required' },
        { status: 400 }
      );
    }

    // Validate email format
    if (!email.includes('@')) {
      return NextResponse.json(
        { error: 'Please enter a valid email address' },
        { status: 400 }
      );
    }

    // Validate first name
    if (!firstName || firstName.trim() === '') {
      return NextResponse.json(
        { error: 'First name is required' },
        { status: 400 }
      );
    }

    // Mailjet API configuration
    const MAILJET_API_KEY = process.env.MAILJET_API_KEY;
    const MAILJET_SECRET_KEY = process.env.MAILJET_SECRET_KEY;

    if (!MAILJET_API_KEY || !MAILJET_SECRET_KEY) {
      console.error('Mailjet environment variables not configured');
      return NextResponse.json(
        { error: 'Email service not configured' },
        { status: 500 }
      );
    }

    // Create base64 encoded credentials for Mailjet
    const credentials = Buffer.from(`${MAILJET_API_KEY}:${MAILJET_SECRET_KEY}`).toString('base64');

    // Format plain text version
    let textPart = 'Bitcoin Through Values - Your Personalised Guide\n\n';
    textPart += `Dear ${firstName.trim()},\n\n`;
    textPart += 'This guide has been customised based on values you\'ve chosen. We hope this helps you convey the value of bitcoin to someone.\n\n';
    
    if (selectedValuesData && Array.isArray(selectedValuesData)) {
      selectedValuesData.forEach((value: { title: string; bulletPoints: string[] }) => {
        textPart += `${value.title}\n`;
        value.bulletPoints.forEach((point: string) => {
          textPart += `• ${point}\n`;
        });
        textPart += '\n';
      });
    }

    // Prepare email content
    const emailHTML = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
          ${guideContent}
          <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e5e5e5; text-align: center; color: #666; font-size: 14px;">
            <p>This guide was generated by <a href="https://bitcointreasurysolutions.com.au/values" style="color: #b28a44; text-decoration: none;">Bitcoin Treasury Solutions</a></p>
          </div>
        </body>
      </html>
    `;

    // Send email using Mailjet
    const mailjetResponse = await fetch('https://api.mailjet.com/v3.1/send', {
      method: 'POST',
      headers: {
        'Authorization': `Basic ${credentials}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        Messages: [
          {
            From: {
              Email: 'noreply@btreasury.com.au',
              Name: 'BTreasury'
            },
            To: [
              {
                Email: email,
                Name: firstName.trim()
              }
            ],
            Subject: 'Your personalised values guide',
            HTMLPart: emailHTML,
            TextPart: textPart
          }
        ]
      }),
    });

    if (!mailjetResponse.ok) {
      const errorData = await mailjetResponse.json();
      console.error('Mailjet API error:', errorData);
      return NextResponse.json(
        { error: 'Failed to send guide. Please try again.' },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true });

  } catch (error) {
    console.error('Send guide error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

